package com.homearound.www.homearound.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CUSTOMER_JOB".
 */
public class CustomerJob {

    private Long id;
    private String jobcategory;
    private Double jobcost;
    private String jobdetail;
    private String jobstatus;
    private String jobtitle;
    private String timecreated;
    private String timefinish;

    public CustomerJob() {
    }

    public CustomerJob(Long id) {
        this.id = id;
    }

    public CustomerJob(Long id, String jobcategory, Double jobcost, String jobdetail, String jobstatus, String jobtitle, String timecreated, String timefinish) {
        this.id = id;
        this.jobcategory = jobcategory;
        this.jobcost = jobcost;
        this.jobdetail = jobdetail;
        this.jobstatus = jobstatus;
        this.jobtitle = jobtitle;
        this.timecreated = timecreated;
        this.timefinish = timefinish;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getJobcategory() {
        return jobcategory;
    }

    public void setJobcategory(String jobcategory) {
        this.jobcategory = jobcategory;
    }

    public Double getJobcost() {
        return jobcost;
    }

    public void setJobcost(Double jobcost) {
        this.jobcost = jobcost;
    }

    public String getJobdetail() {
        return jobdetail;
    }

    public void setJobdetail(String jobdetail) {
        this.jobdetail = jobdetail;
    }

    public String getJobstatus() {
        return jobstatus;
    }

    public void setJobstatus(String jobstatus) {
        this.jobstatus = jobstatus;
    }

    public String getJobtitle() {
        return jobtitle;
    }

    public void setJobtitle(String jobtitle) {
        this.jobtitle = jobtitle;
    }

    public String getTimecreated() {
        return timecreated;
    }

    public void setTimecreated(String timecreated) {
        this.timecreated = timecreated;
    }

    public String getTimefinish() {
        return timefinish;
    }

    public void setTimefinish(String timefinish) {
        this.timefinish = timefinish;
    }

}
