package com.homearound.www.homearound.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.homearound.www.homearound.db.CustomerJob;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CUSTOMER_JOB".
*/
public class CustomerJobDao extends AbstractDao<CustomerJob, Long> {

    public static final String TABLENAME = "CUSTOMER_JOB";

    /**
     * Properties of entity CustomerJob.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Jobcategory = new Property(1, String.class, "jobcategory", false, "JOBCATEGORY");
        public final static Property Jobcost = new Property(2, Double.class, "jobcost", false, "JOBCOST");
        public final static Property Jobdetail = new Property(3, String.class, "jobdetail", false, "JOBDETAIL");
        public final static Property Jobstatus = new Property(4, String.class, "jobstatus", false, "JOBSTATUS");
        public final static Property Jobtitle = new Property(5, String.class, "jobtitle", false, "JOBTITLE");
        public final static Property Timecreated = new Property(6, String.class, "timecreated", false, "TIMECREATED");
        public final static Property Timefinish = new Property(7, String.class, "timefinish", false, "TIMEFINISH");
    };


    public CustomerJobDao(DaoConfig config) {
        super(config);
    }
    
    public CustomerJobDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CUSTOMER_JOB\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"JOBCATEGORY\" TEXT," + // 1: jobcategory
                "\"JOBCOST\" REAL," + // 2: jobcost
                "\"JOBDETAIL\" TEXT," + // 3: jobdetail
                "\"JOBSTATUS\" TEXT," + // 4: jobstatus
                "\"JOBTITLE\" TEXT," + // 5: jobtitle
                "\"TIMECREATED\" TEXT," + // 6: timecreated
                "\"TIMEFINISH\" TEXT);"); // 7: timefinish
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CUSTOMER_JOB\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CustomerJob entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String jobcategory = entity.getJobcategory();
        if (jobcategory != null) {
            stmt.bindString(2, jobcategory);
        }
 
        Double jobcost = entity.getJobcost();
        if (jobcost != null) {
            stmt.bindDouble(3, jobcost);
        }
 
        String jobdetail = entity.getJobdetail();
        if (jobdetail != null) {
            stmt.bindString(4, jobdetail);
        }
 
        String jobstatus = entity.getJobstatus();
        if (jobstatus != null) {
            stmt.bindString(5, jobstatus);
        }
 
        String jobtitle = entity.getJobtitle();
        if (jobtitle != null) {
            stmt.bindString(6, jobtitle);
        }
 
        String timecreated = entity.getTimecreated();
        if (timecreated != null) {
            stmt.bindString(7, timecreated);
        }
 
        String timefinish = entity.getTimefinish();
        if (timefinish != null) {
            stmt.bindString(8, timefinish);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CustomerJob readEntity(Cursor cursor, int offset) {
        CustomerJob entity = new CustomerJob( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // jobcategory
            cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2), // jobcost
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // jobdetail
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // jobstatus
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // jobtitle
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // timecreated
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // timefinish
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CustomerJob entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setJobcategory(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setJobcost(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
        entity.setJobdetail(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setJobstatus(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setJobtitle(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTimecreated(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTimefinish(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CustomerJob entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CustomerJob entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
