package com.homearound.www.homearound.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CUSTOMER_MESSAGE".
 */
public class CustomerMessage {

    private Long id;
    private String direction;
    private String email;
    private String messagebody;
    private String messagetime;
    private String name;

    public CustomerMessage() {
    }

    public CustomerMessage(Long id) {
        this.id = id;
    }

    public CustomerMessage(Long id, String direction, String email, String messagebody, String messagetime, String name) {
        this.id = id;
        this.direction = direction;
        this.email = email;
        this.messagebody = messagebody;
        this.messagetime = messagetime;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDirection() {
        return direction;
    }

    public void setDirection(String direction) {
        this.direction = direction;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMessagebody() {
        return messagebody;
    }

    public void setMessagebody(String messagebody) {
        this.messagebody = messagebody;
    }

    public String getMessagetime() {
        return messagetime;
    }

    public void setMessagetime(String messagetime) {
        this.messagetime = messagetime;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
