package com.homearound.www.homearound.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.homearound.www.homearound.db.CustomerJobDao;
import com.homearound.www.homearound.db.CustomerServiceDao;
import com.homearound.www.homearound.db.CustomerMessageDao;
import com.homearound.www.homearound.db.CustomerMessageBoxDao;
import com.homearound.www.homearound.db.MerchantJobDao;
import com.homearound.www.homearound.db.MerchantMessageDao;
import com.homearound.www.homearound.db.MerchantMessageBoxDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        CustomerJobDao.createTable(db, ifNotExists);
        CustomerServiceDao.createTable(db, ifNotExists);
        CustomerMessageDao.createTable(db, ifNotExists);
        CustomerMessageBoxDao.createTable(db, ifNotExists);
        MerchantJobDao.createTable(db, ifNotExists);
        MerchantMessageDao.createTable(db, ifNotExists);
        MerchantMessageBoxDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        CustomerJobDao.dropTable(db, ifExists);
        CustomerServiceDao.dropTable(db, ifExists);
        CustomerMessageDao.dropTable(db, ifExists);
        CustomerMessageBoxDao.dropTable(db, ifExists);
        MerchantJobDao.dropTable(db, ifExists);
        MerchantMessageDao.dropTable(db, ifExists);
        MerchantMessageBoxDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(CustomerJobDao.class);
        registerDaoClass(CustomerServiceDao.class);
        registerDaoClass(CustomerMessageDao.class);
        registerDaoClass(CustomerMessageBoxDao.class);
        registerDaoClass(MerchantJobDao.class);
        registerDaoClass(MerchantMessageDao.class);
        registerDaoClass(MerchantMessageBoxDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
