package com.homearound.www.homearound.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.homearound.www.homearound.db.CustomerJob;
import com.homearound.www.homearound.db.CustomerService;
import com.homearound.www.homearound.db.CustomerMessage;
import com.homearound.www.homearound.db.CustomerMessageBox;
import com.homearound.www.homearound.db.MerchantJob;
import com.homearound.www.homearound.db.MerchantMessage;
import com.homearound.www.homearound.db.MerchantMessageBox;

import com.homearound.www.homearound.db.CustomerJobDao;
import com.homearound.www.homearound.db.CustomerServiceDao;
import com.homearound.www.homearound.db.CustomerMessageDao;
import com.homearound.www.homearound.db.CustomerMessageBoxDao;
import com.homearound.www.homearound.db.MerchantJobDao;
import com.homearound.www.homearound.db.MerchantMessageDao;
import com.homearound.www.homearound.db.MerchantMessageBoxDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig customerJobDaoConfig;
    private final DaoConfig customerServiceDaoConfig;
    private final DaoConfig customerMessageDaoConfig;
    private final DaoConfig customerMessageBoxDaoConfig;
    private final DaoConfig merchantJobDaoConfig;
    private final DaoConfig merchantMessageDaoConfig;
    private final DaoConfig merchantMessageBoxDaoConfig;

    private final CustomerJobDao customerJobDao;
    private final CustomerServiceDao customerServiceDao;
    private final CustomerMessageDao customerMessageDao;
    private final CustomerMessageBoxDao customerMessageBoxDao;
    private final MerchantJobDao merchantJobDao;
    private final MerchantMessageDao merchantMessageDao;
    private final MerchantMessageBoxDao merchantMessageBoxDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        customerJobDaoConfig = daoConfigMap.get(CustomerJobDao.class).clone();
        customerJobDaoConfig.initIdentityScope(type);

        customerServiceDaoConfig = daoConfigMap.get(CustomerServiceDao.class).clone();
        customerServiceDaoConfig.initIdentityScope(type);

        customerMessageDaoConfig = daoConfigMap.get(CustomerMessageDao.class).clone();
        customerMessageDaoConfig.initIdentityScope(type);

        customerMessageBoxDaoConfig = daoConfigMap.get(CustomerMessageBoxDao.class).clone();
        customerMessageBoxDaoConfig.initIdentityScope(type);

        merchantJobDaoConfig = daoConfigMap.get(MerchantJobDao.class).clone();
        merchantJobDaoConfig.initIdentityScope(type);

        merchantMessageDaoConfig = daoConfigMap.get(MerchantMessageDao.class).clone();
        merchantMessageDaoConfig.initIdentityScope(type);

        merchantMessageBoxDaoConfig = daoConfigMap.get(MerchantMessageBoxDao.class).clone();
        merchantMessageBoxDaoConfig.initIdentityScope(type);

        customerJobDao = new CustomerJobDao(customerJobDaoConfig, this);
        customerServiceDao = new CustomerServiceDao(customerServiceDaoConfig, this);
        customerMessageDao = new CustomerMessageDao(customerMessageDaoConfig, this);
        customerMessageBoxDao = new CustomerMessageBoxDao(customerMessageBoxDaoConfig, this);
        merchantJobDao = new MerchantJobDao(merchantJobDaoConfig, this);
        merchantMessageDao = new MerchantMessageDao(merchantMessageDaoConfig, this);
        merchantMessageBoxDao = new MerchantMessageBoxDao(merchantMessageBoxDaoConfig, this);

        registerDao(CustomerJob.class, customerJobDao);
        registerDao(CustomerService.class, customerServiceDao);
        registerDao(CustomerMessage.class, customerMessageDao);
        registerDao(CustomerMessageBox.class, customerMessageBoxDao);
        registerDao(MerchantJob.class, merchantJobDao);
        registerDao(MerchantMessage.class, merchantMessageDao);
        registerDao(MerchantMessageBox.class, merchantMessageBoxDao);
    }
    
    public void clear() {
        customerJobDaoConfig.getIdentityScope().clear();
        customerServiceDaoConfig.getIdentityScope().clear();
        customerMessageDaoConfig.getIdentityScope().clear();
        customerMessageBoxDaoConfig.getIdentityScope().clear();
        merchantJobDaoConfig.getIdentityScope().clear();
        merchantMessageDaoConfig.getIdentityScope().clear();
        merchantMessageBoxDaoConfig.getIdentityScope().clear();
    }

    public CustomerJobDao getCustomerJobDao() {
        return customerJobDao;
    }

    public CustomerServiceDao getCustomerServiceDao() {
        return customerServiceDao;
    }

    public CustomerMessageDao getCustomerMessageDao() {
        return customerMessageDao;
    }

    public CustomerMessageBoxDao getCustomerMessageBoxDao() {
        return customerMessageBoxDao;
    }

    public MerchantJobDao getMerchantJobDao() {
        return merchantJobDao;
    }

    public MerchantMessageDao getMerchantMessageDao() {
        return merchantMessageDao;
    }

    public MerchantMessageBoxDao getMerchantMessageBoxDao() {
        return merchantMessageBoxDao;
    }

}
